name: Build WAR file and docker image

on:
    workflow_call:
        inputs:
            repo_name:
                type: string
                description: The name of the calling repository
                required: true
            build_number:
                type: string
                description: The build number
                required: true
            build_docker_image:
                type: boolean
                description: Whether to build and upload a docker image
                default: true
                required: false

        secrets:
            SETTINGS_XML:
                required: true
                description: Maven settings.xml file

permissions:
    contents: read
    checks: write # to publish test results

jobs:
    build:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        steps:
            -   name: Dump github context
                run: echo "$GITHUB_CONTEXT"
                shell: bash
                env:
                    GITHUB_CONTEXT: ${{ toJson(github) }}

            -   uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: microsoft
                    cache: maven

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
                if: inputs.build_docker_image

            -   name: Setup settings.xml
                run: echo "${SETTINGS_XML}" >> our-settings.xml
                env:
                    SETTINGS_XML: ${{ secrets.SETTINGS_XML }}

            -   name: Run tests
                run: mvn --batch-mode test -T 1C -s our-settings.xml

            -   name: Deploy maven artifacts to staging repository
                run: mvn --batch-mode deploy -T 1C -s our-settings.xml -P release-deploy -DskipTests -Drevision=${{ inputs.build_number }}

            -   name: Build and export docker webapp image
                uses: docker/build-push-action@v2
                if: inputs.build_docker_image
                with:
                    context: webapp
                    tags: ${{ inputs.repo_name }}:latest
                    outputs: type=docker,dest=/tmp/${{ inputs.repo_name }}.tar
                    cache-from: type=registry,ref=user/app:latest
                    cache-to: type=inline

            -   name: Upload docker image for tomcat webapp
                uses: actions/upload-artifact@v2
                if: inputs.build_docker_image
                with:
                    name: ${{ inputs.repo_name }}
                    path: /tmp/${{ inputs.repo_name }}.tar

            -   name: Publish Test Results
                uses: mikepenz/action-junit-report@v3
                if: always()
                with:
                    check_name: Unit test report
                    report_paths: '**/target/surefire-reports/*.xml'

            -   name: Clean cache
                if: always()
                run: |
                    find ~/.m2/repository/ -name '*.war'
                    find ~/.m2/repository/ -name '*.war' -delete